In [43]:
import pandas as pd
import numpy as np

In [44]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [45]:
df = pd.read_csv('/content/drive/My Drive/Dataset/owid-covid-data.csv')
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166321,ZWE,Africa,Zimbabwe,2022-03-01,236871.0,491.0,413.000,5395.0,0.0,1.000,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
166322,ZWE,Africa,Zimbabwe,2022-03-02,237503.0,632.0,416.286,5396.0,1.0,1.143,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
166323,ZWE,Africa,Zimbabwe,2022-03-03,237503.0,0.0,362.286,5396.0,0.0,0.857,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
166324,ZWE,Africa,Zimbabwe,2022-03-04,238739.0,1236.0,467.429,5397.0,1.0,0.714,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
166325,ZWE,Africa,Zimbabwe,2022-03-05,239019.0,280.0,459.429,5397.0,0.0,0.571,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166326 entries, 0 to 166325
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    166326 non-null  object
 1   continent                                   156370 non-null  object
 2   location                                    166326 non-null  object
 3   date                                        166326 non-null  object
 4   total_cases                                 163293 non-null  float64
 5   new_cases                                   163133 non-null  float64
 6   new_cases_smoothed                          161150 non-null  float64
 7   total_deaths                                145451 non-null  float64
 8   new_deaths                                  145487 non-null  float64
 9   new_deaths_smoothed                         143390 non-null  float64
 10  total_cases_per_million                     162535 non-null  float64
 11  new_cases_per_million                       162375 non-null  float64
 12  new_cases_smoothed_per_million              160398 non-null  float64
 13  total_deaths_per_million                    144706 non-null  float64
 14  new_deaths_per_million                      144742 non-null  float64
 15  new_deaths_smoothed_per_million             142651 non-null  float64
 16  reproduction_rate                           125820 non-null  float64
 17  icu_patients                                23463 non-null   float64
 18  icu_patients_per_million                    23463 non-null   float64
 19  hosp_patients                               24617 non-null   float64
 20  hosp_patients_per_million                   24617 non-null   float64
 21  weekly_icu_admissions                       5433 non-null    float64
 22  weekly_icu_admissions_per_million           5433 non-null    float64
 23  weekly_hosp_admissions                      10923 non-null   float64
 24  weekly_hosp_admissions_per_million          10923 non-null   float64
 25  new_tests                                   67317 non-null   float64
 26  total_tests                                 69255 non-null   float64
 27  total_tests_per_thousand                    69255 non-null   float64
 28  new_tests_per_thousand                      67317 non-null   float64
 29  new_tests_smoothed                          84035 non-null   float64
 30  new_tests_smoothed_per_thousand             84035 non-null   float64
 31  positive_rate                               78655 non-null   float64
 32  tests_per_case                              78084 non-null   float64
 33  tests_units                                 86386 non-null   object
 34  total_vaccinations                          45194 non-null   float64
 35  people_vaccinated                           42987 non-null   float64
 36  people_fully_vaccinated                     40241 non-null   float64
 37  total_boosters                              17539 non-null   float64
 38  new_vaccinations                            37447 non-null   float64
 39  new_vaccinations_smoothed                   84398 non-null   float64
 40  total_vaccinations_per_hundred              45194 non-null   float64
 41  people_vaccinated_per_hundred               42987 non-null   float64
 42  people_fully_vaccinated_per_hundred         40241 non-null   float64
 43  total_boosters_per_hundred                  17539 non-null   float64
 44  new_vaccinations_smoothed_per_million       84398 non-null   float64
 45  new_people_vaccinated_smoothed              83088 non-null   float64
 46  new_people_vaccinated_smoothed_per_hundred  83088 non-null   float64
 47  stringency_index                            130072 non-null  float64
 48  population                                  165251 non-null  float64
 49  population_density                          147928 non-null  float64
 50  median_age                                  137831 non-null  float64
 51  aged_65_older                               136337 non-null  float64
 52  aged_70_older                               137092 non-null  float64
 53  gdp_per_capita                              138504 non-null  float64
 54  extreme_poverty                             91215 non-null   float64
 55  cardiovasc_death_rate                       136778 non-null  float64
 56  diabetes_prevalence                         143949 non-null  float64
 57  female_smokers                              106050 non-null  float64
 58  male_smokers                                104595 non-null  float64
 59  handwashing_facilities                      68569 non-null   float64
 60  hospital_beds_per_thousand                  123664 non-null  float64
 61  life_expectancy                             155268 non-null  float64
 62  human_development_index                     136253 non-null  float64
 63  excess_mortality_cumulative_absolute        5696 non-null    float64
 64  excess_mortality_cumulative                 5696 non-null    float64
 65  excess_mortality                            5696 non-null    float64
 66  excess_mortality_cumulative_per_million     5696 non-null    float64
dtypes: float64(62), object(5)
memory usage: 85.0+ MB

In [47]:
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,1.632930e+05,1.631330e+05,1.611500e+05,1.454510e+05,145487.000000,143390.000000,162535.000000,162375.000000,160398.000000,144706.000000,...,106050.000000,104595.000000,68569.000000,123664.000000,155268.000000,136253.000000,5.696000e+03,5696.000000,5696.000000,5696.000000
mean,2.536044e+06,1.157084e+04,1.156560e+04,5.766407e+04,171.137304,172.673031,29447.756785,166.431538,165.507110,509.384956,...,10.627229,32.778221,50.788710,3.027816,73.576309,0.725587,3.761302e+04,9.404336,15.967077,972.197816
std,1.543441e+07,8.442598e+04,8.257830e+04,3.021145e+05,832.251328,817.024076,51852.379656,683.021740,532.174029,784.551311,...,10.558306,13.523688,31.811788,2.450110,7.491615,0.149964,1.043065e+05,16.439173,30.092830,1420.342295
min,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000,0.000000,0.001000,0.000000,0.000000,0.000000,...,0.100000,7.700000,1.188000,0.100000,53.280000,0.394000,-3.772610e+04,-28.450000,-95.920000,-1826.595723
25%,2.001000e+03,1.000000e+00,7.000000e+00,7.900000e+01,0.000000,0.143000,623.579000,0.042000,1.630000,18.580250,...,1.900000,21.600000,19.351000,1.300000,69.500000,0.602000,-7.515000e+01,-0.722500,-0.752500,-29.788442
50%,2.611700e+04,7.900000e+01,1.071430e+02,7.830000e+02,2.000000,2.429000,4731.521000,11.439000,18.829000,127.737500,...,6.300000,31.400000,49.839000,2.400000,75.050000,0.743000,3.424600e+03,6.065000,7.195000,473.393182
75%,2.987020e+05,1.063000e+03,1.146000e+03,7.307000e+03,20.000000,21.286000,37724.466000,101.289500,120.859750,711.954750,...,19.300000,41.300000,83.241000,4.000000,78.930000,0.845000,2.478462e+04,14.520000,22.997500,1656.361067
max,4.451295e+08,4.206334e+06,3.444237e+06,5.995245e+06,18020.000000,14689.143000,706541.904000,51427.491000,16052.608000,6322.263000,...,44.000000,78.100000,100.000000,13.800000,86.750000,0.957000,1.080748e+06,111.010000,374.930000,9153.060433

In [48]:
df.groupby('iso_code').size()

iso_code
ABW    723
AFG    741
AGO    716
AIA    708
ALB    740
      ...
WSM    473
YEM    695
ZAF    758
ZMB    718
ZWE    716
Length: 238, dtype: int64

In [49]:
df.groupby('continent').size()

continent
Africa           39417
Asia             36200
Europe           37088
North America    24931
Oceania           9217
South America     9517
dtype: int64

In [50]:
df.groupby('location').size()

location
Afghanistan          741
Africa               752
Albania              740
Algeria              740
Andorra              734
                    ...
Wallis and Futuna    503
World                774
Yemen                695
Zambia               718
Zimbabwe             716
Length: 238, dtype: int64

In [51]:
df.isnull().sum()

iso_code                                        0
continent                                    9956
location                                        0
date                                            0
total_cases                                  3033
                                            ...
human_development_index                     30073
excess_mortality_cumulative_absolute       160630
excess_mortality_cumulative                160630
excess_mortality                           160630
excess_mortality_cumulative_per_million    160630
Length: 67, dtype: int64

In [63]:
X = df.iloc[:,4:53].values

In [53]:
X

array([[5.0, 5.0, nan, ..., 18.6, 2.581, 1.337],
       [5.0, 0.0, nan, ..., 18.6, 2.581, 1.337],
       [5.0, 0.0, nan, ..., 18.6, 2.581, 1.337],
       ...,
       [237503.0, 0.0, 362.286, ..., 19.6, 2.822, 1.882],
       [238739.0, 1236.0, 467.429, ..., 19.6, 2.822, 1.882],
       [239019.0, 280.0, 459.429, ..., 19.6, 2.822, 1.882]], dtype=object)

In [55]:
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 29] = labelencoder_X.fit_transform(X[:, 29])

In [56]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.NAN, strategy= 'median', fill_value='Nan', verbose=1, copy=True)
imputer  = imputer.fit(X[:, 0:49])
X[:, 0:49] = imputer.transform(X[:, 0:49])

/usr/local/lib/python3.9/dist-packages/sklearn/impute/_base.py:382: FutureWarning: The 'verbose' parameter was deprecated in version 1.1 and will be removed in 1.3. A warning will always be raised upon the removal of empty columns in the future version.
  warnings.warn(

In [57]:
X

array([[5.0, 5.0, 107.143, ..., 18.6, 2.581, 1.337],
       [5.0, 0.0, 107.143, ..., 18.6, 2.581, 1.337],
       [5.0, 0.0, 107.143, ..., 18.6, 2.581, 1.337],
       ...,
       [237503.0, 0.0, 362.286, ..., 19.6, 2.822, 1.882],
       [238739.0, 1236.0, 467.429, ..., 19.6, 2.822, 1.882],
       [239019.0, 280.0, 459.429, ..., 19.6, 2.822, 1.882]], dtype=object)

In [58]:
df['continent'] = df['continent'].fillna(df['continent'].mode()[0])

In [59]:
y = df['continent']

In [60]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 0])

In [61]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X = sc_X.fit_transform(X)

In [62]:
X

array([[-0.16279805, -0.1356658 , -0.13654204, ..., -1.42990402,
        -1.0299668 , -1.01625567],
       [-0.16279805, -0.13572559, -0.13654204, ..., -1.42990402,
        -1.0299668 , -1.01625567],
       [-0.16279805, -0.13572559, -0.13654204, ..., -1.42990402,
        -1.0299668 , -1.01625567],
       ...,
       [-0.14727194, -0.13572559, -0.13340403, ..., -1.30927131,
        -0.98712766, -0.87470309],
       [-0.14719114, -0.12094555, -0.13211087, ..., -1.30927131,
        -0.98712766, -0.87470309],
       [-0.14717283, -0.13237736, -0.13220927, ..., -1.30927131,
        -0.98712766, -0.87470309]])